"""Add extraction_method to document_pages

Revision ID: b30c27dc02ab
Revises: bd4a89d86c86
Create Date: 2026-08-25 12:30:51.062759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30c27dc02ab'
down_revision: Union[str, Sequence[str], None] = 'bd4a89d86c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_pages', sa.Column('extraction_method', sa.String(length=20), server_default='pymupdf', nullable=False))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_pages', 'extraction_method')
    # ### end Alembic commands ###
